language: c
before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ trusty main restricted'
    - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ trusty main universe'
    - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ trusty main multiverse'
    - sudo apt-get update
    - sudo apt-get install build-essential git-core
    - sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
    - sudo apt-get install qemu-user qemu-system-arm
install:

before_script:

script:
    - sh ./build_all.sh
    - sh ./run_test.sh

after_success:

after_failure:

after_script:

